### PR TITLE
fix/update-api-docs-readme

### PR DESCRIPTION
**Pull request by sunbryely-influxdata**
updating api-docs readme with additional installation of npm packages

Closes #

_Describe your proposed changes here._
add installation guide for redoc, redoc-cli and redocly-openapi-cli

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

### CODE REVIEW

**Comment by sunbryely-influxdata** [comment]
@jstirnaman 
how many people should I be adding to these types of PR requests? 
is there a specific format for the branch title i should be following?
do we usually merge directly into master?

**Review by jstirnaman — CHANGES_REQUESTED** [review]
The team shouldn't need to install these packages; the scripts use `npx` to fetch them and execute the commands. I would be OK with making your addition a developer's note,

Also, I forgot that I've made some updates to this README and scripts in [the v2.2 branch](https://github.com/influxdata/docs-v2/blob/oss-2.2-base/api-docs/README.md) (that we expected to release a while ago).

Sorry for the confusion.

**Comment by jstirnaman** [comment]
> @jstirnaman how many people should I be adding to these types of PR requests? is there a specific format for the branch title i should be following? do we usually merge directly into master?

For docs content PRs, we ideally want one Docs team member, the Product Manager, and maybe the engineer involved. For docs technical/pipeline changes, request Scott or me (esp. for API stuff).

**Comment by sunbryely-influxdata** [comment]
> The team shouldn't need to install these packages; the scripts use `npx` to fetch them and execute the commands. I would be OK with making your addition a developer's note.
> 
> Also, I forgot that I've made some updates to this README and scripts in [the v2.2 branch](https://github.com/influxdata/docs-v2/blob/oss-2.2-base/api-docs/README.md) (that we expected to release a while ago).
> 
> Sorry for the confusion.

No worries, thanks for the clarification. I didn't see your updates and I'll close out / remove this PR since my changes unnecessary after seeing the v2.2 branch

**Pull request closed without merging**
