### PR TITLE
feat: add new config value log-timedout-queries

### PR DESCRIPTION
**Pull request by jeffreyssmith2nd**
- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

### CODE REVIEW

**Comment by sanderson** [comment]
@jeffreyssmith2nd Is this a new configuration option to InfluxDB 1.8 or will this be part of a future patch release?

**Comment by jeffreyssmith2nd** [comment]
New option in 1.11.x https://github.com/influxdata/influxdb/pull/24048

I wasn't sure exactly if this was the right place to put it, if its not I'm happy to move it.

**Comment by sanderson** [comment]
@jeffreyssmith2nd Gotcha. This should actually be added to the InfluxDB Enterprise 1.11 documentation. We didn't have a branch cut for 1.11 yet, but I just did it. It's the `enterprise-1.11` branch and here's the file this should be added to: https://github.com/influxdata/docs-v2/blob/enterprise-1.11/content/enterprise_influxdb/v1.11/administration/configure/config-data-nodes.md

**Comment by jeffreyssmith2nd** [comment]
Thanks @sanderson, I'll close this PR and open a new one pointed at the right content and branch.

**Pull request closed without merging**
