### PR TITLE
Fix regexp example in regular-expressions.md

### PR DESCRIPTION
**Pull request by sickfabian**
Fixes problem in regexp example.

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

### CODE REVIEW

**Comment by sickfabian** [comment]
!signed-cla

**Review by jstirnaman — APPROVED** [review]
Thanks!

**Comment by jstirnaman** [comment]
@sickfabian Hi, if you can please sign the CLA for our repo, then I'll merge your PR.

**Comment by sickfabian** [comment]
Now `!signed-cla`

**Pull request merged**
