### PR TITLE
URL validation on custom URL

### LINKED ISSUE #1739: Add URL validation to custom URL selector
We need to add validation to the custom URL selector to protect against any errors or socially engineered URLs from being used.

### PR DESCRIPTION
**Pull request by sanderson**
Closes #1739

This adds some basic validation on the URL form that should prevent any potential socially engineered vulnerability. It ensures the protocol is http[s] and checks against special characters in the domain.

- [x] Tests pass (no build errors)
- [x] Rebased/mergeable

### CODE REVIEW

**Comment by pierwill** [comment]
The custom URL selector isn't showing up for me locally.
Screen Shot 2020-11-05 at 9 32 57 AM

**Review by pierwill — CHANGES_REQUESTED** [review]
Not running correctly locally...

**Comment by sanderson** [comment]
Are you seeing any JS errors in your browser console?

**Comment by sanderson** [comment]
@pierwill Nevermind. The URL selector modal is now context-sensitive. If you're in the cloud docs, you wont' be able to select the custom URL. If you're in the OSS docs, you will. If you're anywhere else in the docs, you'll see options for both cloud and OSS.

**Comment by pierwill** [comment]
👍

**Review by pierwill — APPROVED** [review]

**Pull request merged**
