### PR TITLE
fix: Authorization, not Authentication, header

### PR DESCRIPTION
**Pull request by jstirnaman**
(closes https://github.com/influxdata/DAR/issues/241)

### CODE REVIEW

**Review by kelseiv — APPROVED** [review]

**Comment by kelseiv** [comment]
@jstirnaman to be sure, does it make sense to update any of the following occurrences?:

 ```
  QuerystringAuthentication:
      type: apiKey
      in: query
      name: u=&p=
      description: >
        ### Querystring authentication scheme

```

`BasicAuthentication:`
or
`2. Configure InfluxDB authentication:`

**Comment by jstirnaman** [comment]
> @jstirnaman to be sure, does it make sense to update any of the following occurrences?:
> 
> ```
>  QuerystringAuthentication:
>      type: apiKey
>      in: query
>      name: u=&p=
>      description: >
>        ### Querystring authentication scheme
> ```
> 
> `BasicAuthentication:` or `2. Configure InfluxDB authentication:`

No, it's confusing, but "Authentication" is the "let me do this" process. "Authorization" is the HTTP header that tells the server what kind of creds you're sending. That's not be confused with, `/authorizations` in InfluxDB which manages tokens and their association to permissions.

**Comment by kelseiv** [comment]
> No, it's confusing, but "Authentication" is the "let me do this" process. "Authorization" is the HTTP header that tells the server what kind of creds you're sending. That's not be confused with, `/authorizations` in InfluxDB which manages tokens and their association to permissions.

Thanks, @jstirnaman! OK, whatever we can say throughout to make this less confusing (and consistent) throughout the v2/Cloud docs the better...fwiw, here's where we landed with authentication/authorization in the enterprise docs cc @pierwill. I imagine we want to be consistent across those as well (unless any surrounding functionality has intentionally changed).

**Comment by pierwill** [comment]
We should be careful with this. In English, I think we'd say that this process of passing a token constitutes *authentication*. But `Authorization: TOKEN` standard scheme, yes? @jstirnaman @sanderson. Even if the docs are *about authentication*, if the API expects `Authorization: TOKEN`, that's what the example should say.

**Comment by sanderson** [comment]
`Authorization` is a [standard HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization) used for authenticating with a service. It supports multiple schemes (Token, Bearer, Basic, etc.).

In regards to language, this is how I view the two terms:

- Authentication: the _process_ of authenticating with a service with defined credentials (username/password, token, etc.) to prove you are who you say you are.
- Authorization: a _set of permissions_ granted to the authenticated client to perform actions within the service.

**Pull request merged**
