### PR TITLE
fix: the cli expects snake case for data_type in csv

### PR DESCRIPTION
**Pull request by jeffreyssmith2nd**
Closes https://github.com/influxdata/influxdb/issues/23807

- [x] Rebased/mergeable

### CODE REVIEW

**Comment by sanderson** [comment]
@jeffreyssmith2nd While I'm ok with this change, it does contradict https://github.com/influxdata/docs-v2/issues/4563 (and https://github.com/influxdata/docs-v2/commit/b69ca52fda5b2078e9f57772c0701464d7b3d58f). It appears there is a product issue here. The UI and CLI seem to be expecting different headers in the CSV.

**Comment by jeffreyssmith2nd** [comment]
> @jeffreyssmith2nd While I'm ok with this change, it does contradict #4563 (and [b69ca52](https://github.com/influxdata/docs-v2/commit/b69ca52fda5b2078e9f57772c0701464d7b3d58f)). It appears there is a product issue here. The UI and CLI seem to be expecting different headers in the CSV.

Ah that is interesting. That implies to me that the CLI just doesn't work as is then, which is a good argument for changing in there instead.

**Comment by sanderson** [comment]
It may not be the CLI. I ran into an issue yesterday where none of the CSV files I was using to test in the UI were working with either header. I think there may be issues in how the UI is parsing bucket-schema CSV files that are uploaded.

**Comment by jeffreyssmith2nd** [comment]
Closing in favor of https://github.com/influxdata/influx-cli/pull/449

**Pull request closed without merging**
