### PR TITLE
Update string.md for convert_ws and uuid

### PR DESCRIPTION
**Pull request by DG12**
usage for convert_ws used convert

example for uuid used upper

Closes #

_Describe your proposed changes here._

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

### CODE REVIEW

**Comment by DG12** [comment]
!signed-cla

InfluxData Contributor License Agreement
Your response has been recorded.

**Comment by DG12** [comment]
!signed-cla

**Comment by DG12** [comment]
!signed-cla

**Review by sanderson — APPROVED** [review]
Thanks @DG12!

**Pull request merged**
