### PR TITLE
Fixed typo in install.md

### PR DESCRIPTION
**Pull request by gijsdb**
Fixed typo on line 387

### CODE REVIEW

**Review by jstirnaman — APPROVED** [review]

**Comment by jstirnaman** [comment]
@gijsdb Thank you for the correction! If you can [sign the CLA](https://www.influxdata.com/legal/cla/), then I'll merge it.

**Comment by gijsdb** [comment]
> @gijsdb Thank you for the correction! If you can [sign the CLA](https://www.influxdata.com/legal/cla/), then I'll merge it.

I can sign it but your CONTRIBUTING.md says: 
"Note: Typo and broken link fixes are greatly appreciated and do not require signing the CLA."

**Comment by gijsdb** [comment]
!signed-cla

**Comment by jstirnaman** [comment]
> > @gijsdb Thank you for the correction! If you can [sign the CLA](https://www.influxdata.com/legal/cla/), then I'll merge it.
> 
> I can sign it but your CONTRIBUTING.md says: "Note: Typo and broken link fixes are greatly appreciated and do not require signing the CLA."

Thanks - I didn't realize that. I only saw the CI blocker.

**Pull request merged**
