### PR TITLE
fix(pagerduty): update pagerduty sendevent function

### PR DESCRIPTION
**Pull request by BondAnthony**
Update pagerduty.sendEvent parameters have changed

Closes #

_Describe your proposed changes here._

- [X] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [X] Rebased/mergeable

### CODE REVIEW

**Comment by BondAnthony** [comment]
@sanderson hopefully I have this correct based on https://github.com/influxdata/flux/blob/45dd7d56bb905708ad1b86b7f8f00f8c97f77b53/stdlib/pagerduty/pagerduty.flux

**Review by sanderson — CHANGES_REQUESTED** [review]
Thanks @BondAnthony (sorry for just getting to this, been away from work).

Can you add in the description of the `eventAction` parameter what `component` was removed? Here's the markdown:

~~~md
### eventAction
[Event type](https://developer.pagerduty.com/docs/events-api-v1/overview/#event-types) to send to PagerDuty.

_**Data type:** String_
~~~

**Comment by BondAnthony** [comment]
@sanderson welcome back! I hope you enjoyed your time away.

I updated the pr, is this what your looking for?

**Review by sanderson — APPROVED** [review]
👌 Perfect. Thanks @BondAnthony!

**Pull request merged**
